version: '3.8'

services:
  fastapi:
    build: .
    env_file: .env
    volumes:
      - ./:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - FACESWAP_API_URL=${FACESWAP_API_URL}
      - RESULT_API_URL=${RESULT_API_URL}
